variables:
  PROJECT_DIR: $CI_PROJECT_DIR
  IMAGE_NAME: registry.gitlab.com/yourbandy-group/backend/pystval

stages:
  - test
  - build

linter_check:
  image: IMAGE_NAME
  script:
    - echo "Running linter..."
    - docker run --security-opt seccomp=unconfined -v $CI_PROJECT_DIR:/app IMAGE_NAME cargo clippy -- -D warnings

test_with_coverage:
  image: IMAGE_NAME
  script:
    - echo "Running tests..."
    - docker run --security-opt seccomp=unconfined -v $CI_PROJECT_DIR:/app IMAGE_NAME cargo tarpaulin --engine llvm --out xml --output-dir ./coverage/
  artifacts:
    paths:
      - ./coverage/*.xml
  needs:
    - job: linter_check
      artifacts: true
