stages:
  - cache
  - build
  - run

cache:
  key: cargo-dependencies
  paths:
    - /usr/local/cargo
    - ./.cargo/

build image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull registry.gitlab.com/yourbandy-group/backend/pystval:latest
    - docker build --cache-from registry.gitlab.com/yourbandy-group/backend/pystval:latest -t registry.gitlab.com/yourbandy-group/backend/pystval:latest .
    - docker push registry.gitlab.com/yourbandy-group/backend/pystval:latest

run:
  stage: run
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker run --security-opt seccomp=unconfined registry.gitlab.com/yourbandy-group/backend/pystval:latest cargo tarpaulin
