# image: python:3.10

# stages:
#   - lint-test
#   - test
#   - build
#   - publish

# variables:
#   PYTHON: "python3.10"
#   CARGO_BUILD_JOBS: 1

# cache:
#   key: "${CI_JOB_NAME}"
#   paths:
#     - target/
#     - .cargo/

# before_script:
#   - curl https://sh.rustup.rs -sSf | sh -s -- -y
#   - export PATH="$HOME/.cargo/bin:$PATH"
#   - rustup update
#   - rustup component add rustfmt clippy
#   - cargo install cargo-tarpaulin
#   - pip install maturin

# lint:
#   stage: lint-test
#   only:
#     - merge_requests
#   tags:
#     - production_runner
#   script:
#     - cargo fmt -- --check

# test:
#   stage: lint-test
#   only:
#     - merge_requests
#   tags:
#     - production_runner
#   script:
#     - cargo tarpaulin --engine llvm --out Xml
#   artifacts:
#     reports:
#       junit: cobertura.xml
#   needs: ["lint"]

# build:
#   stage: build
#   only:
#     - tags
#   tags:
#     - production_runner
#   script:
#     - maturin build --release --strip --manylinux off --interpreter ${PYTHON}
#   artifacts:
#     paths:
#       - target/wheels/*.whl

# publish:
#   stage: publish
#   tags:
#     - production_runner
#   script:
#     - pip install gitlab-artifact-uploader
#     - gitlab-artifact-uploader --base-url $CI_API_V4_URL --token $CI_JOB_TOKEN --job-id $CI_JOB_ID --project-id $CI_PROJECT_ID --file target/wheels/*.whl
#   only:
#     - tags
