stages:
  - linter-test
lint:
  image:
    name: registry.gitlab.com/yourbandy-group/backend/pystval
    entrypoint: [""]
  script:
    - echo "Running linter..."
    - docker run --security-opt seccomp=unconfined -v $CI_PROJECT_DIR:/app registry.gitlab.com/yourbandy-group/backend/pystval cargo clippy -- -D warnings
