[package]
name = "pystval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pystval"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version="0.18.1",features = ["abi3", "abi3-py310"]}
pyo3-asyncio = { version = "0.18", features = ["attributes", "async-std-runtime"] }
async-std = "1.12.0"
thiserror = "1.0.40"
regex = "1.8.1"
lazy_static = "1.4.0"
futures = "0.3.28"
async-mutex = "1.4.0"
[package.metadata.maturin]
category = "tool"

