[package]
name = "pystval"
version = "1.1.0"
authors = ["Mansur Azatbek <mansur62624@gmail.com>"]
description = "Library for creating a custom validator"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pystval"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = {version="0.18.1",features = ["abi3", "abi3-py37","generate-import-lib","multiple-pymethods"] }
pyo3-asyncio = { version = "0.18", features = ["attributes", "async-std-runtime"] }
async-std = {version = "1.12.0",features = ["attributes"]}
# Используем разные виды regex для различной сложности выражений 
#=========================
fancy-regex = "0.11.0"
regex = "1.8.1"
#=========================
lazy_static = "1.4.0"
log = "0.4.19"
env_logger = "0.10.0"
grex = "1.4.1"

[package.metadata.maturin]
category = "tool"
