[package]
name = "pystval"
version = "2.0.0"
authors = ["Mansur Azatbek <mansur62624@gmail.com>"]
description = "Library for creating a custom validator"
edition = "2021"
rust-version = "1.60"


[lib]
name = "pystval"
crate-type = ["cdylib", "rlib"]


# Core library dependencies
[dependencies]
serde = { version = "1.0.180", features = ["derive"], optional = true }
env_logger = "0.10.0"
log = "0.4.19"
async-std = { version = "1.12.0", features = ["attributes"] }
async-trait = "0.1.72"
lazy_static = "1.4.0"
fancy-regex = "0.11.0"
regex = "1.9.1"
indexmap = "2.0.0"
# Next are the optional libraries for building for other targets


# Python bindings
# ========================================================
pyo3 = { version = "0.19.1", optional = true, features = [
    "abi3",
    "abi3-py37",
    "generate-import-lib",
    "multiple-pymethods",
] }
pyo3-asyncio = { version = "0.19", optional = true, features = [
    "attributes",
    "async-std-runtime",
    "testing",
] }
# ========================================================


# Wasm bindings
# ========================================================
wasm-bindgen = { version = "0.2.87", optional = true }
wasm-bindgen-futures = { version = "0.4.37", optional = true }
serde-wasm-bindgen = { version = "0.5.0", optional = true }
# ========================================================


# Module and library switcher for compilations for different platforms
# To maximize flexibility and support for different features or platforms, 
# our project uses conditional compilation. 
# With this approach, we can determine which parts of the code will be included in the final build, 
# depending on the build configuration.

# Add new libraries in a format for different purposes
# --------------------------------------------------------
#    custom-lib = { version = "x.x.x", optional=true } 
# --------------------------------------------------------

# specify in `features` any name for future compilations
# --------------------------------------------------------
#    custom_name_feautre = ["dep:custom-lib"]
# --------------------------------------------------------
# more information at https://doc.rust-lang.org/cargo/reference/features.html


# ========================================================
[features]
python-lib = ["dep:pyo3", "dep:pyo3-asyncio"]
python-lib-build = ["pyo3/extension-module"]
wasm = [
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:serde-wasm-bindgen",
    "dep:serde",
    "indexmap/serde",
]
serde = ["dep:serde", "indexmap/serde"]
# ========================================================


# Another metadata
[package.metadata.maturin]
category = "tool"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
serde_json = "1.0.104"


[[test]]
name = "tests-python-api"
path = "tests/python/tests_python_async.rs"
harness = false
