site_name: Pystval documentation
repo_url: https://github.com/m62624/pystval.git
site_author: m62624

theme:
  name: readthedocs

plugins:
  - search
  - include-markdown
  - exclude:
      glob:
        - images/*
        - scheme/*
        - examples/*

nav:
  - Home: index.md
  - Getting started: getting-started/mod.md
  - Debug & logs: debug_and_Logs.md
  - Modifiers: modifiers.md
  - Formating messages: formatting_the_error_message.md
  - Syntax Regex: syntax_regex/regex.md
  - Requirements: requirements.md
  - Changelog: changelog.md
  - License: LICENSE.md
