site_name: Flexible Inspect Docs
repo_url: https://github.com/m62624/flexible_inspect
site_author: m62624
theme: 
  language: en
  name: material
  logo: logo/png/icon-mini.png
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: orange
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: teal
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started: getting-started/mod.md
  - Debug & logs: debug_and_logs.md
  - Modifiers: modifiers/mod.md
  - Formating messages: formatting_the_error_message.md
  - Changelog: CHANGELOG.md
  - Website materials: website-materials.md
  - Library license: LICENSE.md
