site_name: Pystval documentation
repo_url: https://github.com/m62624/pystval.git
theme:
  name: readthedocs
plugins:
  - include-markdown
  - exclude:
      glob:
        - images/*
        - scheme/*
        - examples/*
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav: 
  - Home: index.md
  - Getting started: getting_started.md
  - Changelog: changelog.md
  - License: LICENSE.md


