name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  IMAGE_DOCKER: ghcr.io/${{ secrets.NAME_LOGIN }}/flexible_inspect:latest
  MODE_PYTHON_VERSION: dist

jobs:
  BUILD_IMAGE_DOCKER:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        run: echo ${{ secrets.DOCKER_KEY }} | docker login ghcr.io -u ${{ secrets.NAME_LOGIN }} --password-stdin
      - name: Clone code
        uses: actions/checkout@v3
      - name: Build image docker (dependencies)
        run: |
          docker pull ${{ env.IMAGE_DOCKER }} || true
          docker build --cache-from ${{ env.IMAGE_DOCKER }} -t ${{ env.IMAGE_DOCKER }} .
          docker push ${{ env.IMAGE_DOCKER }}
